---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dex
  namespace: networking
spec:
  releaseName: dex
  interval: 10m
  chart:
    spec:
      chart: dex
      version: 0.9.0
      sourceRef:
        kind: HelmRepository
        name: dex
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/dexidp/dex
      tag: v2.33.0
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        external-dns/is-public: "true"
      hosts:
        - host: &host dex.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
          secretName: dex-tls
    resources:
      requests:
        cpu: 50m
        memory: 200Mi
      limits:
        cpu: 200m
        memory: 200Mi
    # see https://github.com/dexidp/dex/issues/2082
    env:
      KUBERNETES_POD_NAMESPACE: networking
    config:
      issuer: https://dex.${SECRET_DOMAIN}
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: ${DEX_GITHUB_CLIENT_ID}
            clientSecret: ${DEX_GITHUB_CLIENT_SECRET}
            redirectURI: https://dex.${SECRET_DOMAIN}/callback
            orgs:
              - name: filipweilid-home
                teams:
                  - developers
      staticClients:
        - name: oauth2-proxy
          id: ${DEX_OAUTH2_PROXY_CLIENT_ID}
          secret: ${DEX_OAUTH2_PROXY_CLIENT_SECRET}
          redirectURIs:
            - https://auth.${SECRET_DOMAIN}/oauth2/callback
      storage:
        type: kubernetes
        config:
          inCluster: true
      frontend:
        theme: dark
        issuer: filipweilid
        issuerUrl: https://${SECRET_DOMAIN}
        logoUrl: https://imgur.com/Idzzln9.png
      expiry:
        signingKeys: 6h
        idTokens: 24h
      logger:
        level: debug
        format: json
      oauth2:
        responseTypes: ["code", "token", "id_token"]
        skipApprovalScreen: true
        alwaysShowLoginScreen: true
