---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: poracle
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: kah-common-chart
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    podSecurityContext:
      supplementalGroups:
        - 100
    service:
      main:
        ports:
          http:
            port: 3030
    env:
      PORACLE_SERVER_HOST: 0.0.0.0
      PORACLE_SERVER_PORT: 3030
      PORACLE_DB_TYPE: mysql
      PORACLE_DB_HOST: ${LB_MARIADB}
      PORACLE_DB_DATABASE: poracle
    envFrom:
      - secretRef:
          name: poracle-secrets
    controller:
      replicas: 1
      strategy: RollingUpdate
    image:
      repository: ghcr.io/kartuludus/poraclejs
      tag: develop
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-staging"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: "{{ .Release.Name }}-tls"
    persistence:
      config:
        enabled: true
        type: nfs
        server: "192.168.0.12"
        path: /mnt/hdd/k3s/nfs/poracle-config
        mountPath: /usr/src/app/config/
        readonly: false
      logs:
        enabled: true
        type: pvc
        existingClaim: poracle-logs-v1
        mountPath: /usr/src/app/logs/
      cache:
        enabled: true
        type: pvc
        existingClaim: poracle-cache-v1
        mountPath: /usr/src/app/.cache/
