---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysql
  namespace: databases
spec:
  interval: 15m
  chart:
    spec:
      chart: mysql
      version: 9.2.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 15m
  values:
    image:
      registry: docker.io
      repository: bitnami/mysql
      tag: 8.0.29-debian-11-r9
    primary:
      service:
        type: LoadBalancer
        loadBalancerIP: ${LB_MYSQL}
      persistence:
        args:
          - "--disable-log-bin"
        existingClaim: mysql-pvc
      resources:
        requests:
          cpu: 10m
          memory: 717M
        limits:
          # cpu: 15m
          memory: 1031M
    auth:
      existingSecret: mysql-secrets
      database: rdmdb
      username: rdmuser
    metrics:
      enabled: true
      image:
        registry: docker.io
        repository: bitnami/mysqld-exporter
        tag: 0.14.0-debian-11-r14
      serviceMonitor:
        enabled: true
        namespace: databases
        interval: 3m
        scrapeTimeout: 1m
      resources:
        requests:
          cpu: 10m
          memory: 32M
        limits:
          # cpu: 15m
          memory: 34M
