---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: downloads
spec:
  interval: 10m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: qbittorrent
      version: 13.5.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  dependsOn:
    - name: downloads-gateway
      namespace: vpn
  values:
    image:
      repository: ghcr.io/k8s-at-home/qbittorrent
      tag: v4.4.3.1

    env:
      TZ: "Europe/Stockholm"

    hostname: qbittorrent

    podAnnotations:
      setGateway: "true"

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-staging"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: cloud-download
        hosts:
          - host: "qbittorrent.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: qbittorrent-tls
            hosts:
              - "qbittorrent.${SECRET_DOMAIN}"

    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
    startupProbe:
      enabled: false

    podSecurityContext:
      supplementalGroups:
        - 100

    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent-config
      media:
        enabled: true
        type: nfs
        server: "192.168.0.12"
        path: /mnt/hdd/k3s/nfs/media
        mountPath: /downloads
        readonly: false
    metrics:
      enabled: true
      prometheusRule:
        enabled: true
      exporter:
        env:
          user: ${QBITTORRENT_USER}
          password: ${QBITTORRENT_PASSWORD}
