---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: democratic-csi-nfs
  namespace: democratic-csi
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://democratic-csi.github.io/charts/
      chart: democratic-csi
      version: 0.13.3
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
  values:
    csiDriver:
      name: "org.democratic-csi.truenas-nfs"

    driver:
      # see the driver-config-secret.yaml template for syntax
      existingConfigSecret: secret-democratic-csi-driver-config-nfs
      config:
        ## NOTE: if setting an existing secret you must still set `driver.config.driver`
        ## to the appropriate (equivalent) 'driver' value used in the secret,
        ## as the value is used by the chart for other purposes beyond secret creation
        driver: freenas-nfs

    controller:
      podAnnotations:
        secret.reloader.stakater.com/reload: secret-democratic-csi-driver-config-nfs

    storageClasses:
      - name: csi-truenas-nfs
        defaultClass: false
        reclaimPolicy: Delete # Delete, Retain
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: nfs
        mountOptions:
          - noatime
          - nfsvers=4
          - sec=sys
        secrets:
          provisioner-secret:
          controller-publish-secret:
          node-stage-secret:
          node-publish-secret:
          controller-expand-secret:
