---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 10m
  chart:
    spec:
      # renovate: registryUrl=https://charts.rook.io/release
      chart: rook-ceph-cluster
      version: v1.9.7
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system
  dependsOn:
    - name: rook-ceph
  values:
    monitoring:
      enabled: true
    ingress:
      dashboard:
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-staging"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
        hosts:
          - host: "rook.${SECRET_DOMAIN}"
            paths:
              - "/"
        tls:
          - secretName: rook-tls
            hosts:
              - "rook.${SECRET_DOMAIN}"
    cephClusterSpec:
      dashboard:
        enabled: true
        urlPrefix: /
        ssl: false
